### ISSUE TITLE
Paladins loading screen portraits?

### ISSUE THREAD

**Issue by terzom** [luissilva1044894/hirez-api-docs#11]
Is there a way to get the image of each champion portraits that is shown when a game is about the start (the loading screen)?

Example of what I mean:
https://i.imgur.com/L0Y6dCS.png

**Comment by luissilva1044894** [comment]
Not actually. Unlike Smite, Paladins devs doesn't care about maintaining game assets (skin splash arts, profile avatars, and so). I ask Aaron many times about a CDN and got: It hasn't been a priority for anyone and no one want to take CDN responsibilites.

The closest could be using skin art or champ art as splash art.  Box used to be a way to get some assets, but it's now abandoned: https://app.box.com/s/nmc36gmcc3cv8eekpxt1phm1o1465azl 

May be possible unpack/extract them directly from game files.

**Comment by terzom** [comment]
Alright, thanks for the respond. I am working on a project and would like those portrait since I think players would recognise them the most.

I'll see if I can install the game and if it's possible to extract. 

Thanks

**Comment by luissilva1044894** [comment]
Sometimes `SkinId` are not populated, but you may use skin art too...

https://github.com/luissilva1044894/hirez-api-docs/blob/4e5cafba43a31fe8c93df473f556832e75cb43d5/api/get-match-player-details/paladins.json#L95

But same issue, not all arts are available. Feel free to PR if you get some skins arts!

**Comment by terzom** [comment]
I've made a pull request regarding this. So this issue can be closed. #12
